<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>CsvReporter</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <!-- <ProjectReference Include="../../CatalyticKit/CatalyticKit/CatalyticKit.csproj" /> -->
        <PackageReference Include="CatalyticKit" Version="*" />
    </ItemGroup>

</Project>
